[versions]
junit = "5.11.0"
annotations = "24.0.1"
commonmark = "0.22.0"
lsp4j = "0.23.1"
asm = "9.7.1" # Fabric mixin uses this version, meaning that it will be available in minecraft without us having to bundle it

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher"}
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
commonmark-core = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmark-tables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmark-strikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j"}
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm"}
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm"}
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm"}
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm"}
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm"}

[bundles]
commonmark = ["commonmark-core", "commonmark-tables", "commonmark-strikethrough"]
asm = ["asm-core", "asm-tree", "asm-commons", "asm-util", "asm-analysis"]