name: Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: The type of release
        required: true
        type: choice
        options: ["release", "beta", "alpha"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Read  version
        id: versions
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          all: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.versions.outputs.version }}"
          prerelease: "${{ inputs.version-type != 'release' }}"
          name: "${{ steps.versions.outputs.version }}"
          body_path: changelog/${{ steps.versions.outputs.version }}.md
          files: |
            ./build/libs/*.jar
            ./tools/doctool/build/libs/*.jar
            ./tools/lang-server/build/libs/*.jar